name: website

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: gulp

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          repo: killjoy1221/killjoy1221.github.io
          target_branch: master
          build_dir: public
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
