name: website

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Build
        run: |
          pnpm build

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          repo: killjoy1221/killjoy1221.github.io
          target_branch: master
          build_dir: dist
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
